enum TextureKeys {
  Background = 'background',

  LiveAvailable = 'live-available',
  LiveUsed = 'live-used',

  LaserEnd = 'laser-end',
  LaserMiddle = 'laser-middle',

  Coin = 'coin',
  Cookie = 'cookie',

  CloudsSmall = 'clouds-small',
  Clouds = 'Clouds',
  PlayerLeft = 'PlayerLeft',
  PlayerRight = 'PlayerRight',
  PlayerNormal = 'PlayerNormal',
  IslandHill = 'IslandHill',

  Bubble = 'bubble',

  DinoRun1 = 'dino-run-1',
  DinoRun2 = 'dino-run-2',
  DinoRun3 = 'dino-run-3',
  DinoRun4 = 'dino-run-4',
  DinoRun5 = 'dino-run-5',
  DinoRun6 = 'dino-run-6',
  DinoRun7 = 'dino-run-7',
  DinoRun8 = 'dino-run-8',

  DinoDead1 = 'dino-dead-1',
  DinoDead2 = 'dino-dead-2',
  DinoDead3 = 'dino-dead-3',
  DinoDead4 = 'dino-dead-4',
  DinoDead5 = 'dino-dead-5',
  DinoDead6 = 'dino-dead-6',
  DinoDead7 = 'dino-dead-7',
  DinoDead8 = 'dino-dead-8',

  DinoIdle1 = 'dino-idle-1',
  DinoIdle2 = 'dino-idle-2',
  DinoIdle3 = 'dino-idle-3',
  DinoIdle4 = 'dino-idle-4',
  DinoIdle5 = 'dino-idle-5',
  DinoIdle6 = 'dino-idle-6',
  DinoIdle7 = 'dino-idle-7',
  DinoIdle8 = 'dino-idle-8',
  DinoIdle9 = 'dino-idle-9',

  DinoJump1 = 'dino-jump-1',
  DinoJump2 = 'dino-jump-2',
  DinoJump3 = 'dino-jump-3',
  DinoJump4 = 'dino-jump-4',
  DinoJump5 = 'dino-jump-5',
  DinoJump6 = 'dino-jump-6',
  DinoJump7 = 'dino-jump-7',
  DinoJump8 = 'dino-jump-8',
  DinoJump9 = 'dino-jump-9',
  DinoJump10 = 'dino-jump-10',
  DinoJump11 = 'dino-jump-11',
  DinoJump12 = 'dino-jump-12',
  Sky1 = 'sky-1',
  Sky2 = 'sky-2',
  Foreground = 'foreground',
  MidGroud1 = 'mid-1',
  MidGroud2 = 'mid-2',

  MonkeyRun1 = 'monkey-run-1',
  MonkeyRun2 = 'monkey-run-2',
  MonkeyRun3 = 'monkey-run-3',
  MonkeyRun4 = 'monkey-run-4',
  MonkeyRun5 = 'monkey-run-5',
  MonkeyRun6 = 'monkey-run-6',
  MonkeyRun7 = 'monkey-run-7',
}

export default TextureKeys;
